name: Deploy Azure Function

on:
  push:
    paths:
      - 'azure_functions/train/**'
      - 'scripts/collaborative_filtering.py'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install azure-functions

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Function
      uses: Azure/functions-action@v1
      with:
        app-name: modeltrain2
        package: azure_functions/train
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_68FF7B1DD4C7469B8FA2909F95AAAC72 }}

    - name: Azure Logout
      run: az logout
